# Generated by Django 2.2.17 on 2021-01-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_auto_20210111_1401'),
        ('battles', '0004_auto_20210104_1330'),
    ]

    operations = [
    ]
