# Generated by Django 2.2.17 on 2021-01-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        ('battles', '0005_merge_20210111_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='creator_pokemon_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_as_creator_pokemon_1', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='creator_pokemon_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_as_creator_pokemon_2', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='creator_pokemon_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_as_creator_pokemon_3', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='opponent_pokemon_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_as_opponent_pokemon_1', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='opponent_pokemon_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_as_opponent_pokemon_2', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='opponent_pokemon_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_as_opponent_pokemon_3', to='pokemons.Pokemon'),
        ),
        migrations.DeleteModel(
            name='BattleTeam',
        ),
    ]
