# Generated by Django 2.2.17 on 2021-01-13 17:45

from django.db import migrations


def forwards_func(apps, schema_editor):
    Battle = apps.get_model("battles", "Battle")
    BattleTeam = apps.get_model("battles", "BattleTeam")

    for battle_team in BattleTeam.objects.all():
        Battle.objects.filter(
            id=battle_team.battle.id,
        ).update(
            creator_pokemon_1=battle_team.pokemon_1,
            creator_pokemon_2=battle_team.pokemon_2,
            creator_pokemon_3=battle_team.pokemon_3,
        )


def reverse_func(apps, schema_editor):
    Battle = apps.get_model("battles", "Battle")
    BattleTeam = apps.get_model("battles", "BattleTeam")

    for battle_team in BattleTeam.objects.all():
        Battle.objects.filter(
            id=battle_team.battle.id,
        ).update(
            creator_pokemon_1=None,
            creator_pokemon_2=None,
            creator_pokemon_3=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_auto_20210113_1331'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
