# Generated by Django 2.2.17 on 2021-01-11 20:08
from django.db import migrations


def add_pokemons(apps, schema_editor):
    Pokemon = apps.get_model("pokemons", "Pokemon")
    pokemon_1 = Pokemon.objects.create(
        poke_id=1,
        name="bulbasaur",
        attack=65,
        defense=65,
        hit_points=45,
    )
    pokemon_2 = Pokemon.objects.create(
        poke_id=2,
        name="ivysaur",
        attack=80,
        defense=80,
        hit_points=60,
    )
    pokemon_3 = Pokemon.objects.create(
        poke_id=2,
        name="venusaur",
        attack=100,
        defense=100,
        hit_points=80,
    )

    Battle = apps.get_model("battles", "Battle")
    for battle in Battle.objects.all():
        battle.creator_pokemon_1 = pokemon_1
        battle.creator_pokemon_2 = pokemon_2
        battle.creator_pokemon_3 = pokemon_3
        battle.opponent_pokemon_1 = pokemon_3
        battle.opponent_pokemon_2 = pokemon_2
        battle.opponent_pokemon_3 = pokemon_1
        battle.save()


def reverse_add_pokemons(apps, schema_editor):
    Battle = apps.get_model("battles", "Battle")
    for battle in Battle.objects.all():
        battle.creator_pokemon_1 = None
        battle.creator_pokemon_2 = None
        battle.creator_pokemon_3 = None
        battle.opponent_pokemon_1 = None
        battle.opponent_pokemon_2 = None
        battle.opponent_pokemon_3 = None
        battle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_auto_20210111_2005'),
    ]

    operations = [
        migrations.RunPython(add_pokemons, reverse_add_pokemons),
    ]
