# Generated by Django 2.2.17 on 2021-01-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0007_auto_20210113_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BattleTeam',
        ),
    ]
